services:
  ##### Managed Services #####
  qdrant:
    container_name: qdrant_container
    image: qdrant/qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ../docker/dbs/qdrant:/qdrant/storage
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../docker/db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "jeral"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
  mongo-express:
    container_name: mongo_express_containerr
    image: mongo-express:latest
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "jeral"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "1234"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_AUTH_DATABASE: "admin"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: yohan #For browser
      ME_CONFIG_BASICAUTH_PASSWORD: 1234 #For browser
    volumes:
      - ../docker/ms/mongo-express:/config
    depends_on:
      - mongodb
  ##### Services #####
  users-service:
    container_name: users_container
    restart: always
    build:
      context: ../../sitecore-genai-users
      dockerfile: Dockerfile.dev
    ports:
      - "6002:6002"
    environment:
      - PORT=6002
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - DOMAIN=undefined
      - BASE_URL=http://localhost:5173
      - DATABASE_URL=mongodb://jeral:1234@mongodb:27017/users_db?authSource=admin
    volumes:
        - ../../sitecore-genai-users:/app
        - /app/node_modules
    depends_on:
      - mongodb
  gateway-service:
    container_name: gateway_container
    restart: always
    build:
      context: ../../sitecore-genai-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "6000:6000"
    environment:
      - PORT=6000
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5173
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - DOMAIN=undefined
      - BASE_URL=http://localhost:5173
    volumes:
        - ../../sitecore-genai-gateway:/app
        - /app/node_modules
  knowledge-service:
    build:
      context: ../../sitecore-genai-knowledge
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - "QDRANT_URL=http://localhost:6333"
      - "QDRANT_API_KEY=${QDRANT_API_KEY}"
      - "ACCESS_TOKEN=${ACCESS_TOKEN}"
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"
    volumes:
      - ../../sitecore-genai-knowledge:/app
    depends_on:
      - qdrant
  ai-service:
    container_name: ai_container
    restart: always
    build:
      context: ../../sitecore-genai-ai
      dockerfile: Dockerfile.dev
    ports:
      - "6001:6001"
    environment:
      - PORT=6001
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5173
      - KNOWLEDGE_API_URL=http://knowledge-service:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - V0_API_KEY=${V0_API_KEY}
    volumes:
        - ../../sitecore-genai-ai:/app
        - /app/node_modules
  frontend:
    container_name: frontend_container
    restart: always
    build:
      context: ../../sitecore-genai-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:6001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - VITE_DOMAIN=http://localhost:5173
    volumes:
      - ../../sitecore-genai-frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true